version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/
    steps:
      - run:
          name: Install
          command: |
            pwd
            ls
            ./install_ci.sh
            yarn install
      - run:
          name: Running Unit Tests
          command: |
            yarn test:unit
workflows:
  version: 2
  commit:
    jobs:
      - build
