version: 2.0

jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/with-query-router-ci
    steps:
      - checkout
      # https://circleci.com/docs/2.0/yarn/
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Running Tests
          command: |
            yarn test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
